name: fl_stripe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  credit_card_type_detector: ^3.0.0
  dio: ^5.3.3
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.2
  flutter_stripe: ^9.4.0
  go_router: ^11.1.2
  icons_plus: ^4.0.0
  stripe_sdk: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
